{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe52d0ac-5527-4836-bb4e-53479541a778",
   "metadata": {},
   "outputs": [],
   "source": [
    "pip install \"pycozo[embedded,pandas]\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d1eb2727-98cc-4556-87f4-a2ce75bcb64f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pycozo.client import Client\n",
    "import pandas as pd\n",
    "from pycozo.client import Client\n",
    "client = Client('rocksdb', 'Benchmark_cozo.db')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c30c6cdc-280c-42fc-a9d5-26c7310a1325",
   "metadata": {},
   "outputs": [],
   "source": [
    "#transform cozo nodes + prop to csv\n",
    "# this code is used to transform only \n",
    "import os\n",
    "import pandas as pd\n",
    "\n",
    "# 1. Charger les dataframes depuis CozoDB\n",
    "node_label_df = pd.DataFrame(client.run('?[id_n,ln] := *node_label[id_n,ln]'))\n",
    "node_label_df = node_label_df[(node_label_df[\"id_n\"] >= 2900001) &(node_label_df[\"id_n\"] <= 3000000)]\n",
    "\n",
    "\n",
    "node_prop_df  = pd.DataFrame(client.run('?[id_n,key,value] := *node_prop[id_n,key,value]'))\n",
    "node_prop_df = node_prop_df[(node_prop_df[\"id_n\"] >= 2900001) &(node_prop_df[\"id_n\"] <= 3000000)]\n",
    "\n",
    "\n",
    "\n",
    "# 2) Préparer le répertoire de sortie\n",
    "output_dir = \"nodes_csv\"\n",
    "os.makedirs(output_dir, exist_ok=True)\n",
    "\n",
    "# 3) Pour chaque label, construire et écrire le CSV dans ce répertoire\n",
    "for label in node_label_df['ln'].unique():\n",
    "    # IDs pour ce label\n",
    "    ids = node_label_df.loc[node_label_df['ln'] == label, 'id_n']\n",
    "    \n",
    "    # Filtrer les propriétés\n",
    "    props = node_prop_df[node_prop_df['id_n'].isin(ids)]\n",
    "    \n",
    "    # DataFrame de base avec tous les IDs\n",
    "    base = pd.DataFrame({'id_n': ids}).drop_duplicates().set_index('id_n')\n",
    "    \n",
    "    # Pivoter et joindre si des propriétés existent\n",
    "    if not props.empty:\n",
    "        pivot = props.pivot(index='id_n', columns='key', values='value')\n",
    "        df = base.join(pivot, how='left')\n",
    "    else:\n",
    "        df = base.copy()\n",
    "    \n",
    "    # Remettre id_n en colonne\n",
    "    df = df.reset_index()\n",
    "    \n",
    "    # Écrire le fichier CSV dans le répertoire\n",
    "    filename = f\"{label.upper()}.csv\"\n",
    "    path = os.path.join(output_dir, filename)\n",
    "    df.to_csv(path, index=False, encoding='utf-8')\n",
    "\n",
    "print(\"c'est done capitaine pour nodes!\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8fe84ff2-2181-4eb8-8f37-25f4e3091c8c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#transform edge_prop to csv\n",
    "# DO NOT FORGET TO UPDATE the start and end point \n",
    "import os\n",
    "import pandas as pd\n",
    "\n",
    "# Récupérer les données depuis CozoDB\n",
    "edge_label = pd.DataFrame(client.run('?[id_e, ln] := *edge_label[id_e, ln]'))\n",
    "edge_label_df = edge_label[(edge_label[\"id_e\"] >= 16_630_881) &(edge_label[\"id_e\"] <= 16_631_282)]\n",
    "\n",
    "edge = pd.DataFrame(client.run('?[id_e, ns, nd] := *edge[id_e, ns, nd]'))\n",
    "edge_df = edge[(edge[\"id_e\"] >= 16_630_881) &(edge[\"id_e\"] <= 16_631_282)]\n",
    "\n",
    "\n",
    "edge_prop = pd.DataFrame(client.run('?[id_e, key, value] := *edge_prop[id_e, key, value]'))\n",
    "edge_prop_df = edge_prop[(edge_prop[\"id_e\"] >= 16_630_881) &(edge_prop[\"id_e\"] <= 16_631_282)]\n",
    "\n",
    "# 2) Préparer le répertoire de sortie\n",
    "output_dir = \"edges_csv\"\n",
    "os.makedirs(output_dir, exist_ok=True)\n",
    "\n",
    "# 3) Pour chaque label, construire et écrire le CSV dans ce répertoire\n",
    "for label in edge_label_df['ln'].unique():\n",
    "    # 3.1) Tous les id_e pour ce label\n",
    "    ids = edge_label_df.loc[edge_label_df['ln'] == label, 'id_e']\n",
    "    \n",
    "    # 3.2) Extraire from/to pour ces id_e\n",
    "    base = edge_df[edge_df['id_e'].isin(ids)].rename(columns={'ns':'from_id','nd':'to_id'})\n",
    "    base = base.set_index('id_e')\n",
    "    \n",
    "    # 3.3) Filtrer les propriétés de ces id_e\n",
    "    props = edge_prop_df[edge_prop_df['id_e'].isin(ids)]\n",
    "    \n",
    "    # 3.4) Pivoter et joindre si des propriétés existent\n",
    "    if not props.empty:\n",
    "        pivot = props.pivot(index='id_e', columns='key', values='value')\n",
    "        df = base.join(pivot, how='left')\n",
    "    else:\n",
    "        df = base.copy()\n",
    "    \n",
    "    # 3.5) Remettre id_e en colonne\n",
    "    df = df.reset_index()\n",
    "    \n",
    "    # 3.6) Écrire le fichier CSV (nom = label en minuscules)\n",
    "    filename = f\"{label}.csv\"\n",
    "    path = os.path.join(output_dir, filename)\n",
    "    df.to_csv(path, index=False, encoding='utf-8')\n",
    "\n",
    "print(\"edges are done capitain !\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
